language: node_js

node_js:
  - "9"
  - "8"
  - "6"
  - "4"

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g grunt-cli@latest
  - npm install

sudo: false
